import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { Suspense } from "react";
import { parseUICookie } from "@/lib/cookies";
import { UIStoreProvider } from "@/store/use-ui-store";
import { SyncUIState } from "@/components/store-initializer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * 主题初始化脚本：在浏览器渲染 Body 之前同步执行
 * 彻底解决首屏主题闪烁问题
 */
function ThemeScript() {
  return (
    <script
      dangerouslySetInnerHTML={{
        __html: `
          try {
            const match = document.cookie.match(/ui-state=([^;]+)/);
            if (match) {
              const state = JSON.parse(decodeURIComponent(match[1]));
              const theme = state.theme;
              const isDark = theme === 'dark' || (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);
              document.documentElement.classList.toggle('dark', isDark);
              document.documentElement.style.colorScheme = isDark ? 'dark' : 'light';
            }
          } catch (e) {}
        `,
      }}
    />
  );
}

/**
 * 状态同步组件：负责读取 Cookie 并分发 Store
 * 必须在 Suspense 内运行以符合 Next.js 16 规则
 */
async function UIStateSync({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const initialState = parseUICookie(cookieStore.get('ui-state')?.value);

  return (
    <UIStoreProvider initialState={initialState}>
      <SyncUIState />
      {children}
    </UIStoreProvider>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body className="min-h-full flex flex-col">
        <Suspense fallback={null}>
          <UIStateSync>{children}</UIStateSync>
        </Suspense>
      </body>
    </html>
  );
}
